'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, Flame, Leaf, LockKeyhole, Sparkles } from 'lucide-react'

type Challenge = { id: string; title: string; description: string; points: number; icon: string | null; duration: number; topic: string; tasks: { id: string; title: string; description: string | null; why: string | null; points: number; requires_photo: boolean }[] }

type Props = { challenges: Challenge[]; userId: string | null }

const topics = ['Tất cả']

export function ChallengesPage({ challenges, userId }: Props) {
  const [topic, setTopic] = useState('Tất cả')
  const [selected, setSelected] = useState<Challenge | null>(null)
  const [joined, setJoined] = useState<string[]>([])
  const [busy, setBusy] = useState(false)
  const filtered = useMemo(() => topic === 'Tất cả' ? challenges : challenges.filter((item) => item.topic === topic), [challenges, topic])

  async function joinChallenge(challengeId: string) {
    if (!userId) { window.location.href = `/auth/login?next=/thu-thach`; return }
    setBusy(true)
    const response = await fetch('/api/challenges/join', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ challengeId }) })
    if (response.ok) setJoined((items) => items.includes(challengeId) ? items : [...items, challengeId])
    setBusy(false)
  }

  return <main className="min-h-screen bg-[#f8fbf5] text-[#173b2b]">
    <header className="border-b border-[#dcebdc] bg-[#f8fbf5] px-5 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="/" className="font-black tracking-tight">Sống Xanh <span className="text-[#72ad42]">Campus</span></a><a href={userId ? '/profile' : '/auth/login?next=/thu-thach'} className="rounded-full bg-[#173b2b] px-4 py-2 text-sm font-bold text-white">{userId ? 'Hồ sơ' : 'Đăng nhập'}</a></div></header>
    <section className="mx-auto max-w-6xl px-5 pb-10 pt-12"><a href="/" className="text-sm font-bold text-[#5b8067]">← Về trang chủ</a><div className="mt-5 max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#72ad42]">Cùng nhau tạo thay đổi</p><h1 className="mt-3 text-4xl font-black tracking-[-0.05em] sm:text-6xl">Thử thách xanh,<br /><span className="text-[#72ad42]">mỗi ngày một chút.</span></h1><p className="mt-5 text-base leading-7 text-[#64806e]">Chọn một thử thách vừa sức, hoàn thành từng nhiệm vụ và nhìn thấy tác động của mình.</p></div></section>
    <section className="mx-auto max-w-6xl px-5 pb-14"><div className="flex gap-2 overflow-x-auto pb-2" role="tablist" aria-label="Lọc theo chủ đề">{[...topics, ...Array.from(new Set(challenges.map((item) => item.topic).filter(Boolean)))].map((item) => <button key={item} onClick={() => setTopic(item)} className={`shrink-0 rounded-full px-4 py-2.5 text-sm font-bold ${topic === item ? 'bg-[#173b2b] text-white' : 'border border-[#cde6bd] bg-white text-[#4f785b]'}`}>{item}</button>)}</div>{filtered.length === 0 ? <div className="mt-8 rounded-[2rem] border border-dashed border-[#bcd8b3] bg-white p-8 text-center"><Leaf className="mx-auto text-[#72ad42]" /><h2 className="mt-4 text-xl font-black">Chưa có thử thách phù hợp</h2><p className="mt-2 text-sm text-[#5f7967]">Dữ liệu thật sẽ xuất hiện khi biên tập viên thêm thử thách.</p></div> : <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map((challenge) => { const isJoined = joined.includes(challenge.id); return <article key={challenge.id} className="rounded-[1.75rem] border border-[#deecd9] bg-white p-5 shadow-[0_10px_30px_#3c684d0b]"><div className="flex items-start justify-between"><span className="grid size-14 place-items-center rounded-2xl bg-[#e9f6d9] text-2xl">{challenge.icon || '🌱'}</span><span className="rounded-full bg-[#f0f7eb] px-3 py-1 text-xs font-bold text-[#477b50]">{challenge.duration} ngày</span></div><h2 className="mt-6 text-xl font-black">{challenge.title}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-[#5f7967]">{challenge.description}</p><div className="mt-5 flex items-center justify-between text-sm font-bold text-[#5f7967]"><span>{challenge.tasks.length} nhiệm vụ</span><span>+{challenge.points} điểm</span></div><button disabled={busy || isJoined} onClick={() => joinChallenge(challenge.id)} className={`mt-5 flex w-full items-center justify-center rounded-xl py-3 text-sm font-bold ${isJoined ? 'bg-[#e7f4d8] text-[#4b864b]' : 'bg-[#173b2b] text-white'}`}>{isJoined ? <><Check className="mr-2" size={16} /> Đã nhận</> : <>Nhận thử thách <ArrowRight className="ml-2" size={16} /></>}</button><button onClick={() => setSelected(challenge)} className="mt-3 w-full py-2 text-sm font-bold text-[#477b50]">Xem chi tiết</button></article>})}</div>}</section>
    {selected && <div className="fixed inset-0 z-30 grid place-items-end bg-[#173b2b]/30 p-0 sm:place-items-center sm:p-5" role="presentation" onClick={() => setSelected(null)}><section onClick={(event) => event.stopPropagation()} className="max-h-[85vh] w-full overflow-y-auto rounded-t-[2rem] bg-white p-6 sm:max-w-lg sm:rounded-[2rem]" role="dialog" aria-modal="true" aria-labelledby="challenge-title"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#72ad42]">Chi tiết thử thách</p><h2 id="challenge-title" className="mt-2 text-2xl font-black">{selected.title}</h2></div><button onClick={() => setSelected(null)} className="rounded-full bg-[#eef6e8] px-3 py-2 text-sm font-bold">Đóng</button></div><p className="mt-4 text-sm leading-6 text-[#5f7967]">{selected.description}</p><div className="mt-6 flex flex-col gap-3">{selected.tasks.map((task, index) => <div key={task.id} className="flex gap-3 rounded-2xl bg-[#f5faef] p-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#dcefc7] text-sm font-black text-[#477b50]">{index + 1}</span><div><h3 className="font-black">{task.title}</h3><p className="mt-1 text-sm text-[#5f7967]">{task.description || 'Nhiệm vụ xanh mỗi ngày.'}</p>{task.why && <p className="mt-2 text-xs leading-5 text-[#477b50]"><strong>Vì sao có ích:</strong> {task.why}</p>}{task.requires_photo && <p className="mt-2 text-xs font-bold text-[#90683d]">Cần ảnh minh chứng</p>}</div></div>)}</div><button onClick={() => joinChallenge(selected.id)} disabled={busy || joined.includes(selected.id)} className="mt-6 flex w-full items-center justify-center rounded-xl bg-[#173b2b] py-3 text-sm font-bold text-white">{joined.includes(selected.id) ? 'Đã nhận thử thách' : 'Nhận thử thách này'}</button></section></div>}
  </main>
}

export function TodayTasks({ tasks, userId }: { tasks: { challenge_id: string; title: string; duration_days: number; day_number: number; task_id: string; task_title: string; task_description: string | null; why: string | null; points: number; task_day: number; requires_photo: boolean }[]; userId: string }) {
  const [completed, setCompleted] = useState<string[]>([])
  const [impact, setImpact] = useState<string | null>(null)
  async function complete(taskId: string) { const response = await fetch('/api/challenges/complete', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ taskId }) }); const result = await response.json(); if (response.ok) { setCompleted((items) => [...items, taskId]); setImpact(result.impact || null) } }
  return <section className="mx-auto max-w-3xl px-5 py-10"><div className="rounded-[2rem] bg-[#173b2b] p-6 text-white"><div className="flex items-center gap-3"><Flame className="text-[#b8e45c]" /><div><p className="text-xs font-bold uppercase tracking-widest text-[#b8e45c]">Hôm nay</p><h1 className="text-2xl font-black">Nhiệm vụ của bạn</h1></div></div><p className="mt-4 text-sm leading-6 text-[#c2d8c4]">Tối đa 3 nhiệm vụ được tính điểm mỗi ngày để đảm bảo công bằng.</p></div><div className="mt-5 flex flex-col gap-3">{tasks.map((task) => { const done = completed.includes(task.task_id); return <div key={`${task.challenge_id}-${task.task_id}`} className="rounded-2xl border border-[#deecd9] bg-white p-4"><div className="flex items-start gap-3"><span className={`grid size-9 shrink-0 place-items-center rounded-full ${done ? 'bg-[#dcefc7] text-[#477b50]' : 'bg-[#eef6e8] text-[#72ad42]'}`}>{done ? <Check size={17} /> : <Sparkles size={17} />}</span><div className="flex-1"><div className="flex items-center justify-between gap-3"><h2 className="font-black">{task.task_title}</h2><span className="text-xs font-bold text-[#477b50]">Ngày {task.task_day}/{task.duration_days}</span></div><p className="mt-1 text-sm text-[#5f7967]">{task.task_description}</p>{task.why && <p className="mt-2 text-xs leading-5 text-[#477b50]"><strong>Vì sao có ích:</strong> {task.why}</p>}{task.requires_photo && <p className="mt-2 text-xs font-bold text-[#90683d]">Cần ảnh minh chứng</p>}<p className="mt-2 text-sm font-bold text-[#477b50]">+{task.points} điểm</p></div><button disabled={done} onClick={() => complete(task.task_id)} className="rounded-xl bg-[#173b2b] px-3 py-2 text-xs font-bold text-white disabled:bg-[#e7f4d8] disabled:text-[#477b50]">{done ? 'Đã xong' : 'Hoàn thành'}</button></div></div>})}</div>{impact && <div className="mt-5 rounded-2xl border border-[#cde6bd] bg-[#eef8df] p-4 text-sm font-bold text-[#376645]">Tác động quy đổi: {impact}</div>}{tasks.length === 0 && <div className="mt-5 rounded-2xl border border-dashed border-[#bcd8b3] p-7 text-center text-sm text-[#5f7967]">Chưa có nhiệm vụ hôm nay.</div>}</section>
}

export function AuthRequiredToday() { return <div className="mx-auto max-w-xl px-5 py-20 text-center"><LockKeyhole className="mx-auto text-[#72ad42]" size={32} /><h1 className="mt-4 text-3xl font-black">Đăng nhập để xem hôm nay</h1><p className="mt-3 text-[#5f7967]">Bạn cần tài khoản để lưu thử thách, điểm và chuỗi ngày.</p><a href="/auth/login?next=/thu-thach/hom-nay" className="mt-6 inline-flex rounded-full bg-[#173b2b] px-6 py-3 text-sm font-bold text-white">Đăng nhập</a></div> }

