-- Idempotent secure RPCs. Run after schema and RLS; safe to run repeatedly.
create or replace function public.create_commitment_secure(p_title text, p_display_name boolean, p_class_name text default null, p_faculty text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare u uuid:=auth.uid(); cid uuid; begin if u is null then raise exception 'not_authenticated'; end if; if exists(select 1 from public.users where id=u and locked) then raise exception 'account_locked'; end if; if nullif(trim(p_title),'') is null then raise exception 'invalid_title'; end if; if exists(select 1 from public.commitments where user_id=u and title=trim(p_title) and created_at >= now()-interval '1 hour') then raise exception 'duplicate_commitment'; end if; insert into public.commitments(user_id,title,display_name,class_name,faculty) values(u,trim(p_title),coalesce(p_display_name,false),nullif(trim(p_class_name),''),nullif(trim(p_faculty),'')) returning id into cid; return jsonb_build_object('id',cid); end $$;
create or replace function public.save_carbon_result_secure(p_transport numeric,p_food numeric,p_energy numeric,p_shopping numeric,p_total numeric) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare u uuid:=auth.uid(); rid uuid; begin if u is null then raise exception 'not_authenticated'; end if; if exists(select 1 from public.users where id=u and locked) then raise exception 'account_locked'; end if; if least(p_transport,p_food,p_energy,p_shopping,p_total) < 0 or greatest(p_transport,p_food,p_energy,p_shopping,p_total) > 100000 then raise exception 'invalid_carbon_value'; end if; insert into public.carbon_results(user_id,transport_kg,food_kg,energy_kg,shopping_kg,total_kg) values(u,p_transport,p_food,p_energy,p_shopping,p_total) returning id into rid; return jsonb_build_object('id',rid,'total_kg',p_total); end $$;
create or replace function public.complete_task_secure(p_task_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare u uuid:=auth.uid(); t public.tasks%rowtype; c integer; begin if u is null then raise exception 'not_authenticated'; end if; if exists(select 1 from public.users where id=u and locked) then raise exception 'account_locked'; end if; select * into t from public.tasks where id=p_task_id and active; if not found then raise exception 'task_not_found'; end if; if not exists(select 1 from public.user_challenges uc where uc.user_id=u and uc.challenge_id=t.challenge_id) then raise exception 'challenge_not_joined'; end if; if exists(select 1 from public.user_tasks where user_id=u and task_id=p_task_id and status='completed') then raise exception 'task_already_completed'; end if; select count(*) into c from public.user_tasks where user_id=u and status='completed' and (completed_at at time zone 'Asia/Ho_Chi_Minh')::date=(now() at time zone 'Asia/Ho_Chi_Minh')::date; if c>=3 then raise exception 'daily_task_limit'; end if; insert into public.user_tasks(user_id,task_id,status,completed_at) values(u,p_task_id,'completed',now()); update public.users set total_points=coalesce(total_points,0)+t.points,updated_at=now() where id=u; return jsonb_build_object('points',t.points,'impact',jsonb_build_object('points',t.points),'badges','[]'::jsonb); end $$;
create or replace function public.submit_daily_quiz_secure(p_question_id uuid,p_answer text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare u uuid:=auth.uid(); correct boolean; today date:=(now() at time zone 'Asia/Ho_Chi_Minh')::date; current integer:=0; points integer:=0; begin if u is null then raise exception 'not_authenticated'; end if; if exists(select 1 from public.users where id=u and locked) then raise exception 'account_locked'; end if; select correct_answer=p_answer into correct from public.quiz_questions where id=p_question_id and active; if not found then raise exception 'question_not_found'; end if; select coalesce(score,0) into current from public.game_daily_scores where user_id=u and played_on=today for update; current:=coalesce(current,0); if exists(select 1 from public.game_quiz_answers where user_id=u and question_id=p_question_id and played_on=today) then raise exception 'question_already_answered'; end if; if correct then points:=least(3,greatest(0,30-current)); end if; insert into public.game_quiz_answers(user_id,question_id,played_on) values(u,p_question_id,today); insert into public.game_daily_scores(user_id,played_on,score) values(u,today,points) on conflict(user_id,played_on) do update set score=least(30,public.game_daily_scores.score+excluded.score); update public.users set total_points=coalesce(total_points,0)+points where id=u; return jsonb_build_object('correct',correct,'points',points,'score',least(30,current+points)); end $$;
create or replace function public.get_today_challenges() returns setof public.challenges language sql stable security definer set search_path=public,pg_temp as $$ select * from public.challenges where active order by created_at desc limit 3 $$;
create or replace function public.get_daily_game_questions() returns table(id uuid,question text,options jsonb,game_type text) language sql stable security definer set search_path=public,pg_temp as $$ select q.id,q.question,q.options,q.game_type from public.quiz_questions q where q.active and q.game_type='true-false' order by md5(q.id::text||(now() at time zone 'Asia/Ho_Chi_Minh')::date::text) limit 10 $$;
create or replace function public.get_campaign_summary(p_campaign_id uuid) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$ select jsonb_build_object('participants',count(distinct p.user_id),'impact_points',coalesce(sum(coalesce(p.pledge::numeric,0)),0)) from public.pledges p where p.campaign_id=p_campaign_id $$;
create or replace function public.get_leaderboard(p_period text,p_scope text,p_school text,p_faculty text,p_cohort text,p_page integer,p_page_size integer) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$ select jsonb_build_object('people',coalesce(jsonb_agg(jsonb_build_object('rank',rank,'display_name',display_name,'faculty',faculty,'points',total_points)),'[]'::jsonb)) from (select row_number() over(order by total_points desc) rank,display_name,faculty,total_points from public.users where not hide_from_leaderboard and not locked and (p_scope is null or p_scope='all' or school=p_school) and (p_faculty is null or faculty=p_faculty) order by total_points desc limit greatest(p_page_size,1) offset greatest(p_page-1,0)*greatest(p_page_size,1)) x $$;
revoke execute on all functions in schema public from public,anon;
grant execute on function public.get_today_challenges() to anon;
grant execute on function public.get_campaign_summary(uuid) to anon;
grant execute on function public.get_leaderboard(text,text,text,text,text,integer,integer) to anon;
grant execute on all functions in schema public to authenticated;
alter default privileges in schema public revoke execute on functions from public,anon;
