-- Idempotent development seed. Run after functions; safe to run repeatedly.
insert into public.articles(slug,title,excerpt,content,source,featured,published,author_name) select v.slug,v.title,v.excerpt,v.content,v.source,v.featured,true,v.author_name from (values
('guong-sang-song-xanh','Gương sáng sống xanh','Những hành động nhỏ tạo thay đổi lớn.','Sinh viên cùng xây dựng khuôn viên xanh bằng các thói quen bền vững.','Sống Xanh Campus',true,'Ban biên tập'),
('song-xanh-moi-ngay','Kiến thức sống xanh','Hiểu đúng để thực hành tốt hơn.','Tiết kiệm điện, giảm nhựa và phân loại rác đúng cách là những bước khởi đầu.','Sống Xanh Campus',false,'Ban biên tập'),
('tin-xanh-campus','Tin xanh Campus','Cập nhật hoạt động môi trường trong trường.','Các câu lạc bộ đang triển khai nhiều hoạt động xanh thiết thực.','Sống Xanh Campus',false,'Ban biên tập'),
('giao-thong-ben-vung','Giao thông bền vững','Di chuyển xanh cho campus đáng sống.','Ưu tiên đi bộ, xe đạp và phương tiện công cộng khi có thể.','Sống Xanh Campus',false,'Ban biên tập'),
('tieu-dung-co-trach-nhiem','Tiêu dùng có trách nhiệm','Mua ít hơn, dùng lâu hơn.','Chọn sản phẩm bền, sửa chữa và tái sử dụng trước khi mua mới.','Sống Xanh Campus',false,'Ban biên tập')) v(slug,title,excerpt,content,source,featured,author_name) where not exists(select 1 from public.articles a where a.slug=v.slug);
insert into public.quiz_questions(question,options,correct_answer,explanation,active,game_type,source) select v.question,v.options,v.answer,v.explanation,true,'true-false','Sống Xanh Campus' from (values
('Tắt đèn khi rời phòng là thói quen xanh?','["Đúng","Sai"]'::jsonb,'Đúng','Giúp giảm điện năng.'),('Mang bình cá nhân giúp giảm nhựa?','["Đúng","Sai"]'::jsonb,'Đúng','Giảm đồ dùng một lần.'),('Pin cũ có thể bỏ chung với rác sinh hoạt?','["Đúng","Sai"]'::jsonb,'Sai','Pin cần điểm thu gom riêng.'),('Đi xe đạp giúp giảm phát thải?','["Đúng","Sai"]'::jsonb,'Đúng','Không phát thải trực tiếp.'),('Rác hữu cơ có thể ủ phân?','["Đúng","Sai"]'::jsonb,'Đúng','Có thể tạo phân compost.'),('Đốt rác là cách xử lý an toàn?','["Đúng","Sai"]'::jsonb,'Sai','Gây ô nhiễm không khí.'),('Tái sử dụng đồ dùng giúp giảm rác?','["Đúng","Sai"]'::jsonb,'Đúng','Kéo dài vòng đời sản phẩm.'),('Nên rút sạc khi không sử dụng?','["Đúng","Sai"]'::jsonb,'Đúng','Giảm điện tiêu thụ chờ.'),('Khăn giấy bẩn thuộc nhóm giấy tái chế?','["Đúng","Sai"]'::jsonb,'Sai','Cần bỏ vào rác thông thường.'),('Mua vừa đủ giúp giảm lãng phí?','["Đúng","Sai"]'::jsonb,'Đúng','Giảm tiêu dùng và rác thải.')) v(question,options,answer,explanation) where not exists(select 1 from public.quiz_questions q where q.question=v.question);
insert into public.waste_items(name,category,explanation,difficulty) select v.name,v.category,v.explanation,v.difficulty from (values ('Vỏ rau quả','organic','Có thể ủ phân.','Dễ'),('Vỏ chuối','organic','Có thể ủ phân.','Dễ'),('Chai nhựa','recyclable','Làm sạch và bỏ vào nhóm tái chế.','Dễ'),('Lon nhôm','recyclable','Thu gom cùng kim loại tái chế.','Dễ'),('Giấy sạch','recyclable','Giữ khô để tái chế.','Dễ'),('Khăn giấy bẩn','general','Không bỏ vào giấy tái chế.','Dễ'),('Xốp bẩn','general','Bỏ vào rác thông thường.','Trung bình'),('Pin cũ','hazardous','Đưa tới điểm thu gom.','Trung bình'),('Bóng đèn hỏng','hazardous','Xử lý như rác nguy hại.','Khó'),('Thuốc hết hạn','hazardous','Đưa tới điểm thu hồi phù hợp.','Khó')) v(name,category,explanation,difficulty) where not exists(select 1 from public.waste_items w where w.name=v.name);
insert into public.game_scenarios(slug,title,description) values('mot-ngay-sinh-vien','Một ngày sinh viên','Các lựa chọn xanh trong ngày học.') on conflict(slug) do nothing;
insert into public.game_scenario_steps(scenario_id,step_order,prompt,options) select s.id,v.step_order,v.prompt,v.options from public.game_scenarios s cross join (values (1,'Buổi sáng bạn đến trường bằng cách nào?','[{"id":"bike","label":"Xe đạp","planetDelta":3},{"id":"bus","label":"Xe buýt","planetDelta":2},{"id":"motorbike","label":"Xe máy cá nhân","planetDelta":0}]'::jsonb),(2,'Bạn mua đồ uống thế nào?','[{"id":"bottle","label":"Dùng bình cá nhân","planetDelta":3},{"id":"cup","label":"Cốc dùng một lần","planetDelta":0}]'::jsonb),(3,'Sau giờ học, bạn xử lý rác ra sao?','[{"id":"sort","label":"Phân loại đúng","planetDelta":3},{"id":"mixed","label":"Bỏ chung tất cả","planetDelta":0}]'::jsonb)) v(step_order,prompt,options) where s.slug='mot-ngay-sinh-vien' and not exists(select 1 from public.game_scenario_steps x where x.scenario_id=s.id and x.step_order=v.step_order);
insert into public.challenges(slug,title,description,active) select v.slug,v.title,v.description,true from (values ('tiet-kiem-dien','Tiết kiệm điện','Giảm điện năng mỗi ngày.'),('campus-khong-nhua','Campus không nhựa','Giảm đồ dùng một lần.'),('phan-loai-rac','Phân loại rác','Đưa rác về đúng nơi.')) v(slug,title,description) where not exists(select 1 from public.challenges c where c.slug=v.slug);
insert into public.tasks(challenge_id,title,description,points,active) select c.id,v.title,v.description,v.points,true from public.challenges c cross join (values ('Tắt thiết bị khi rời phòng','Tắt đèn và quạt khi không dùng.',5),('Dùng ánh sáng tự nhiên','Mở rèm thay vì bật đèn ban ngày.',5),('Ghi lại mức tiết kiệm','Theo dõi một ngày sử dụng điện.',10)) v(title,description,points) where c.slug='tiet-kiem-dien' and not exists(select 1 from public.tasks t where t.challenge_id=c.id and t.title=v.title);
insert into public.tasks(challenge_id,title,description,points,active) select c.id,v.title,v.description,v.points,true from public.challenges c cross join (values ('Mang bình cá nhân','Không dùng chai nhựa một lần.',5),('Từ chối ống hút nhựa','Chọn đồ uống không kèm ống hút.',5),('Tái sử dụng túi','Mang túi dùng nhiều lần.',10)) v(title,description,points) where c.slug='campus-khong-nhua' and not exists(select 1 from public.tasks t where t.challenge_id=c.id and t.title=v.title);
insert into public.tasks(challenge_id,title,description,points,active) select c.id,v.title,v.description,v.points,true from public.challenges c cross join (values ('Tách rác hữu cơ','Đưa rác hữu cơ vào đúng thùng.',5),('Làm sạch chai lọ','Tráng chai trước khi tái chế.',5),('Đưa pin tới điểm thu gom','Không bỏ pin vào rác thường.',10)) v(title,description,points) where c.slug='phan-loai-rac' and not exists(select 1 from public.tasks t where t.challenge_id=c.id and t.title=v.title);
insert into public.campaigns(slug,title,description,active,published) select 'thang-song-xanh','Tháng sống xanh','Cùng tạo campus bền vững hơn.',true,true where not exists(select 1 from public.campaigns where slug='thang-song-xanh');
insert into public.impact_factors(name,value,unit,source,source_year,active) select v.name,v.value,v.unit,v.source,v.source_year,true from (values ('Đi xe đạp',0.21,'kg CO₂/km','GHG Protocol',2024),('Chai nhựa dùng một lần',0.08,'kg CO₂/chai','EPA',2024),('Điện lưới',0.45,'kg CO₂/kWh','IEA',2024)) v(name,value,unit,source,source_year) where not exists(select 1 from public.impact_factors i where i.name=v.name);
